//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChessGui {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form1() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapChessGui.Form1", typeof(Form1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Boolean podobny do zasobu True.
        /// </summary>
        internal static bool button1_Locked {
            get {
                object obj = ResourceManager.GetObject("button1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Boolean podobny do zasobu True.
        /// </summary>
        internal static bool comboBoxB_Locked {
            get {
                object obj = ResourceManager.GetObject("comboBoxB.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Boolean podobny do zasobu True.
        /// </summary>
        internal static bool comboBoxW_Locked {
            get {
                object obj = ResourceManager.GetObject("comboBoxW.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Boolean podobny do zasobu True.
        /// </summary>
        internal static bool groupBox1_Locked {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Boolean podobny do zasobu True.
        /// </summary>
        internal static bool groupBox2_Locked {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Windows.Forms.ImageListStreamer.
        /// </summary>
        internal static System.Windows.Forms.ImageListStreamer imageList1_ImageStream {
            get {
                object obj = ResourceManager.GetObject("imageList1.ImageStream", resourceCulture);
                return ((System.Windows.Forms.ImageListStreamer)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Point podobny do zasobu {X=6,Y=11}.
        /// </summary>
        internal static System.Drawing.Point imageList1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("imageList1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Boolean podobny do zasobu True.
        /// </summary>
        internal static bool menuStrip1_Locked {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Point podobny do zasobu {X=190,Y=11}.
        /// </summary>
        internal static System.Drawing.Point menuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Boolean podobny do zasobu True.
        /// </summary>
        internal static bool panel1_Locked {
            get {
                object obj = ResourceManager.GetObject("panel1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Boolean podobny do zasobu True.
        /// </summary>
        internal static bool pictureBox1_Locked {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Point podobny do zasobu {X=102,Y=13}.
        /// </summary>
        internal static System.Drawing.Point timer1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
